---
abstract: 'Adds headers to allow Cross-Origin Resource Sharing'
author:
  - 'Graham Knop <haarg@haarg.org>'
build_requires:
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-CrossOrigin
requires:
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  parent: 0
resources:
  bugtracker: http://github.com/haarg/Plack-Middleware-CrossOrigin/issues
  repository: git://github.com/haarg/Plack-Middleware-CrossOrigin.git
version: 0.002
